/**
 * components components barrel export file
 * Version: 1.0.0
 */

// Export components
export { default as UserAuthForm } from './user-auth-form';
export { default as ThemeProvider } from './theme-provider';
export { default as SuspenseUserAuthForm } from './suspense-user-auth-form';
export { default as SiteHeader } from './site-header';
export { default as SiteFooter } from './site-footer';
export { default as SearchParamsFallback } from './search-params-fallback';
export * from './ui/core/tooltip';
export * from './ui/core/textarea';
export * from './ui/core/tabs';
export * from './ui/core/table';
export * from './ui/core/switch';
export * from './ui/core/sonner';
export * from './ui/core/separator';
export * from './ui/core/select';
export * from './ui/core/radio-group';
export * from './ui/core/popover';
export { default as LoadingSpinner } from './ui/core/loading-spinner';
export * from './ui/core/label';
export * from './ui/core/input';
export * from './ui/core/form';
export * from './ui/core/dropdown-menu';
export * from './ui/core/dialog';
export * from './ui/core/checkbox';
export * from './ui/core/card';
export * from './ui/core/button';
export * from './ui/core/badge';
export * from './ui/core/avatar';
export * from './ui/core/alert';
export * from './ui/core/accordion';
export { default as ValidationTierBadge } from './trust/ui/validation-tier-badge';
export { default as TimezoneSelector } from './scheduling/shared/timezone-selector';
export { default as TimeSlotSelector } from './scheduling/client/time-slot-selector';
export { default as SessionTypeSelector } from './scheduling/client/session-type-selector';
export { default as BookingForm } from './scheduling/client/booking-form';
export { default as BookingCalendar } from './scheduling/client/booking-calendar';
export { default as WeeklySchedule } from './scheduling/builder/weekly-schedule';
export { default as SessionTypeEditor } from './scheduling/builder/session-type-editor';
export { default as WeeklyAvailability } from './scheduling/builder/availability/weekly-availability';
export { default as AvailabilityManagement } from './scheduling/builder/availability/availability-management';
export { default as AvailabilityExceptions } from './scheduling/builder/availability/availability-exceptions';
export { default as providers } from './providers/providers';
export { default as ClerkProvider } from './providers/clerk-provider';
export { default as UserProfile } from './profile/user-profile';
export { default as SuccessMetricsDashboard } from './profile/success-metrics-dashboard';
export { default as RoleBadges } from './profile/role-badges';
export { default as ProfileAuthProvider } from './profile/profile-auth-provider';
export { default as PortfolioShowcase } from './profile/portfolio-showcase';
export { default as PortfolioGallery } from './profile/portfolio-gallery';
export * from './profile/client-profile';
export { default as BuilderProfile } from './profile/builder-profile';
export { default as BuilderProfileWrapper } from './profile/builder-profile-wrapper';
export { default as BuilderProfileClientWrapper } from './profile/builder-profile-client-wrapper';
export { default as AppShowcase } from './profile/app-showcase';
export { default as AddProjectForm } from './profile/add-project-form';
export { default as ValidationTierBadge } from './profile/ui/validation-tier-badge';
export { default as SessionBookingCard } from './profile/ui/session-booking-card';
export { default as ProfileStats } from './profile/ui/profile-stats';
export { default as PaymentStatusIndicator } from './payment/payment-status-indicator';
export * from './marketplace/builder-list';
export { default as BuilderImage } from './marketplace/builder-image';
export { default as BuilderDashboard } from './marketplace/builder-dashboard';
export { default as BuilderCard } from './marketplace/builder-card';
export { default as FilterPanel } from './marketplace/ui/filter-panel';
export { default as TestimonialSection } from './marketing/testimonial-section';
export { default as MarketingHero } from './marketing/marketing-hero';
export { default as MarketingHeader } from './marketing/marketing-header';
export { default as MarketingFooter } from './marketing/marketing-footer';
export { default as MarketingCta } from './marketing/marketing-cta';
export { default as FeatureShowcase } from './marketing/feature-showcase';
export { default as FeatureGrid } from './marketing/feature-grid';
export { default as ViewingPreferences } from './marketing/ui/viewing-preferences';
export { default as TrustProofCompanies } from './marketing/ui/trust-proof-companies';
export { default as TestimonialCard } from './marketing/ui/testimonial-card';
export { default as NewsletterForm } from './marketing/ui/newsletter-form';
export { default as MarketingStat } from './marketing/ui/marketing-stat';
export { default as MarketingMarquee } from './marketing/ui/marketing-marquee';
export { default as FeatureCard } from './marketing/ui/feature-card';
export { default as WordRotate } from './magicui/word-rotate';
export { default as TypingAnimation } from './magicui/typing-animation';
export { default as TextAnimate } from './magicui/text-animate';
export * from './magicui/terminal';
export * from './magicui/ripple';
export * from './magicui/particles';
export { default as OrbitingCircles } from './magicui/orbiting-circles';
export { default as marquee } from './magicui/marquee';
export { default as globe } from './magicui/globe';
export { default as DotPattern } from './magicui/dot-pattern';
export * from './magicui/border-beam';
export { default as BlurFade } from './magicui/blur-fade';
export * from './magicui/avatar-circles';
export * from './magicui/aurora-text';
export { AnimatedSubscribeButton } from './animated-subscribe-button';
export { default as AnimatedCircularProgressBar } from './magicui/animated-circular-progress-bar';
export * from './learning/timeline';
export { default as TimelineItem } from './learning/ui/timeline-item';
export { default as TimelineFilter } from './learning/ui/timeline-filter';
export * from './landing/types';
export { default as TrustedEcosystem } from './landing/trusted-ecosystem';
export { default as TestimonialSection } from './landing/testimonial-section';
export { default as SkillsTreeSection } from './landing/skills-tree-section';
export { default as SkillsCarousel } from './landing/skills-carousel';
export { default as PerformanceOptimizations } from './landing/performance-optimizations';
export { default as navbar } from './landing/navbar';
export { default as HeroSection } from './landing/hero-section';
export { default as footer } from './landing/footer';
export { default as FeatureScroll } from './landing/feature-scroll';
export * from './landing/data';
export { default as CtaSection } from './landing/cta-section';
export { default as BentoSection } from './landing/bento-section';
export { default as AiStats } from './landing/ai-stats';
export { default as AiCapabilitiesMarquee } from './landing/ai-capabilities-marquee';
export { default as accessibility } from './landing/accessibility';
export { default as TestimonialScroll } from './landing/ui/testimonial-scroll';
export * from './community/knowledge-base';
export { default as KnowledgeItem } from './community/ui/knowledge-item';
export { default as DiscussionCard } from './community/ui/discussion-card';
export { default as BookingButton } from './booking/booking-button';
export { default as LoadingState } from './auth/loading-state';
export { default as ClerkAuthForm } from './auth/clerk-auth-form';
export { default as AuthStatus } from './auth/auth-status';
export { default as AuthErrorBoundary } from './auth/auth-error-boundary';
export * from './admin/settings-panel';
export { default as SessionTypeForm } from './admin/session-type-form';
export { default as AdminNav } from './admin/admin-nav';
export { default as AdminCard } from './admin/ui/admin-card';
export * from './site-header';
export * from './site-footer';
export * from './theme-provider';
export * from './search-params-fallback';

// Re-export subdirectory
export * from './utils';
