/**
 * Type definitions for Prisma JSON fields
 * Auto-generated by fix-prisma-types.js
 * Version: 0.1.1
 *
 * This is the source of truth for all Prisma-related type definitions.
 */

import { Prisma } from "@prisma/client";

/**
 * SocialLinks type for BuilderProfile
 */
export interface SocialLinks {
  website?: string;
  linkedin?: string;
  github?: string;
  twitter?: string;
  [key: string]: any; // Allow additional properties
}

/**
 * PortfolioItemOutcome type for BuilderProfile
 */
export interface PortfolioItemOutcome {
  label: string;
  value: string;
  trend: 'up' | 'down' | 'neutral';
  type?: string;
  verified?: boolean;
  isVerified?: boolean; // Alternative property name for verification status
  description?: string; // Additional property for longer descriptions
}

/**
 * PortfolioItem type for BuilderProfile
 */
export interface PortfolioItem {
  id: string;
  title: string;
  description: string;
  imageUrl?: string;
  outcomes?: PortfolioItemOutcome[];
  tags?: string[];
  projectUrl?: string;
  createdAt: Date | string;
  client?: string;
  date?: string | Date;
  images?: string[];
  technologies?: string[];
  [key: string]: any; // Allow additional properties
}

// Type utilities for working with Prisma JSON fields
declare global {
  namespace PrismaJson {
    // These types help Prisma understand our JSON structures
    type BuilderProfileSocialLinks = SocialLinks;
    type BuilderProfilePortfolioItem = PortfolioItem;
  }
}

/**
 * Convert SocialLinks to a Prisma-compatible JSON value
 */
export function socialLinksToJson(links?: SocialLinks): Prisma.InputJsonValue | undefined {
  if (!links) return undefined;
  return links as unknown as Prisma.InputJsonValue;
}

/**
 * Convert PortfolioItem[] to a Prisma-compatible JSON array
 */
export function portfolioItemsToJson(items?: PortfolioItem[]): Prisma.InputJsonValue[] | undefined {
  if (!items) return undefined;
  return items as unknown as Prisma.InputJsonValue[];
}

/**
 * Get SocialLinks from a BuilderProfile
 */
export function getSocialLinks(profile: { socialLinks?: Prisma.JsonValue | null }): SocialLinks | undefined {
  if (!profile.socialLinks) return undefined;
  return profile.socialLinks as unknown as SocialLinks;
}

/**
 * Get PortfolioItems from a BuilderProfile
 */
export function getPortfolioItems(profile: { portfolioItems?: Prisma.JsonValue[] }): PortfolioItem[] | undefined {
  if (!profile.portfolioItems || !Array.isArray(profile.portfolioItems)) return undefined;
  return profile.portfolioItems as unknown as PortfolioItem[];
}

// Export the utility functions
export const PrismaJsonUtils = {
  socialLinksToJson,
  portfolioItemsToJson,
  getSocialLinks,
  getPortfolioItems
};

export default PrismaJsonUtils;
