-- Add expertise fields to BuilderProfile
ALTER TABLE "BuilderProfile" 
  ADD COLUMN IF NOT EXISTS "slug" TEXT UNIQUE,
  ADD COLUMN IF NOT EXISTS "tagline" TEXT,
  ADD COLUMN IF NOT EXISTS "displayName" TEXT,
  ADD COLUMN IF NOT EXISTS "completedProjects" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "responseRate" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "expertiseAreas" JSONB,
  ADD COLUMN IF NOT EXISTS "featured" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "clerkUserId" TEXT UNIQUE;